"""Backward-compatibility guard (PLAN.md ground rule 2).

Config files produced by v1.1.9 must keep loading in every later version. These
fixtures were generated by the shipped 1.1.9 code and must never be regenerated
— that is the whole point. When a later phase renames or reshapes a field, the
loader gains an alias and these tests keep passing.
"""

from pathlib import Path

import pytest

from vmctl.core.exceptions import ValidationError
from vmctl.core.vmconfig import (
    DiskFormat,
    Allocation,
    NetworkType,
    BusType,
    VMConfig,
)
from vmctl.serializers.json_serializer import JSONSerializer
from vmctl.serializers.yaml_serializer import YAMLSerializer

CONFIGS = Path(__file__).parent / "fixtures" / "configs"
LEGACY = ["v1_1_9_multidisk", "v1_1_9_multinic"]


@pytest.mark.parametrize("stem", LEGACY)
def test_legacy_yaml_still_loads(stem):
    vm = YAMLSerializer().load(CONFIGS / f"{stem}.yaml")
    assert isinstance(vm, VMConfig)
    assert vm.name
    assert vm.cpu.count >= 1


@pytest.mark.parametrize("stem", LEGACY)
def test_legacy_json_still_loads(stem):
    vm = JSONSerializer().load(CONFIGS / f"{stem}.json")
    assert isinstance(vm, VMConfig)
    assert vm.name


@pytest.mark.parametrize("stem", LEGACY)
def test_legacy_yaml_and_json_describe_the_same_vm(stem):
    y = YAMLSerializer().load(CONFIGS / f"{stem}.yaml")
    j = JSONSerializer().load(CONFIGS / f"{stem}.json")
    assert YAMLSerializer().to_dict(y) == JSONSerializer().to_dict(j)


@pytest.mark.parametrize("stem", LEGACY)
def test_saving_twice_produces_the_same_file(stem, tmp_path):
    """Load/save is a fixed point, so editing one setting shows one line in the diff.

    This is the no-churn guarantee in the form that survives a rename: within a
    version, saving what was loaded changes nothing.
    """
    vm = YAMLSerializer().load(CONFIGS / f"{stem}.yaml")
    first = tmp_path / "first.yaml"
    YAMLSerializer().save(vm, first)
    second = tmp_path / "second.yaml"
    YAMLSerializer().save(YAMLSerializer().load(first), second)
    assert second.read_text() == first.read_text()


#: The whole M-06 rename table, applied below by hand. If vmctl's own upgrade and
#: this literal ever disagree, one of them is wrong -- which is the point.
RENAMED_KINDS = {"hdd": "disk", "ssd": "disk", "dvd": "cdrom"}
RENAMED_DEVICE_KEYS = {
    "type": "kind",
    "variant": "allocation",
    "controller": "bus",  # 1.1.x `controller` named a bus
    "controller_name": "controller",  # ... and `controller_name` named a controller
    "port": "slot",
    "device": "unit",
}
RENAMED_CONTROLLER_KEYS = {"name": "native_name", "controller_type": "bus"}
RENAMED_VM_KEYS = {"ostype": "guest_os"}
RENAMED_NETWORK_KEYS = {"adapter_type": "model"}
#: A chipset id named the card; the model names it neutrally (A-10).
RENAMED_NIC_MODELS = {
    "82540EM": "e1000",
    "82543GC": "e1000",
    "82545EM": "e1000",
    "Am79C970A": "pcnet",
    "Am79C973": "pcnet",
    "virtio": "virtio",
}


def _upgrade(before):
    """Return the 1.1.9 mapping rewritten by hand into today's vocabulary.

    Deliberately literal: it is the rename table from PLAN.md written out, so the
    test compares vmctl's upgrade against an independent statement of it rather
    than against itself.
    """
    after = {RENAMED_VM_KEYS.get(k, k): v for k, v in before.items()}
    devices = after.pop("disks", None)
    if devices is not None:
        after["storage"] = [_upgrade_device(d) for d in devices]
    if after.get("networks"):
        after["networks"] = [_upgrade_network(n) for n in after["networks"]]
    if after.get("storage_controllers"):
        upgraded = []
        seen = {}
        for sc in after["storage_controllers"]:
            renamed = {RENAMED_CONTROLLER_KEYS.get(k, k): v for k, v in sc.items()}
            # The logical id is new information rather than a rename: bus plus how
            # many controllers on that bus came before. Spelled out here instead of
            # calling vmctl's own helper, so the two are independent statements.
            bus = renamed.get("bus", "sata")
            index = seen.get(bus, 0)
            seen[bus] = index + 1
            renamed["id"] = f"{bus}{index}"
            upgraded.append(renamed)
        after["storage_controllers"] = upgraded
    return after


def _upgrade_network(network):
    """Rewrite one 1.1.x network mapping."""
    out = {}
    for key, value in network.items():
        if key == "adapter_type":
            out["model"] = RENAMED_NIC_MODELS[value]
        else:
            out[RENAMED_NETWORK_KEYS.get(key, key)] = value
    return out


def _upgrade_device(device):
    """Rewrite one 1.1.x disk mapping."""
    out = {}
    for key, value in device.items():
        if key == "type":
            kind = RENAMED_KINDS[value]
            out["kind"] = kind
            if value == "ssd":
                out["nonrotational"] = True
            if kind != "disk":
                continue
        else:
            out[RENAMED_DEVICE_KEYS.get(key, key)] = value
    # A drive has no capacity, so the upgraded file does not claim one.
    if out.get("kind") in ("cdrom", "floppy"):
        out.pop("size_mb", None)
    return out


def _model_defaults():
    """Every default the model declares, by field name.

    Used to recognise a key that a 1.1.9 file simply did not have yet, as opposed
    to one whose value changed.
    """
    from dataclasses import MISSING, fields

    from vmctl.core import vmconfig as m

    out = {}
    for name in dir(m):
        dc = getattr(m, name)
        if not (isinstance(dc, type) and hasattr(dc, "__dataclass_fields__")):
            continue
        for f in fields(dc):
            if f.default is not MISSING:
                value = f.default
                out.setdefault(f.name, set()).add(value.value if hasattr(value, "value") else value)
    return out


def _differences(before, after, path=()):
    """Yield ``(path, old, new)`` for every leaf that is not identical.

    A key present on one side only yields ``_ABSENT`` for the other.
    """
    if isinstance(before, dict) and isinstance(after, dict):
        for key in sorted(set(before) | set(after)):
            yield from _differences(
                before.get(key, _ABSENT), after.get(key, _ABSENT), path + (str(key),)
            )
    elif isinstance(before, list) and isinstance(after, list) and len(before) == len(after):
        for i, (b, a) in enumerate(zip(before, after)):
            yield from _differences(b, a, path + (str(i),))
    elif before != after:
        yield path, before, after


_ABSENT = object()


@pytest.mark.parametrize("stem", LEGACY)
def test_upgrading_a_legacy_file_only_renames_what_the_plan_says(stem, tmp_path):
    """Saving a 1.1.9 file with today's vmctl renames vocabulary and nothing else.

    Ground rule 2 promises old files keep loading; it does not promise the words
    never improve. `type: hdd` became `kind: disk` because `hdd` and `ssd` were
    never two kinds of device (M-01), and `disks:` became `storage:` because the
    list holds optical and floppy drives too (M-02).

    So the promise is stated narrowly: apply the documented rename table by hand,
    and every remaining difference must be a field the old version did not have,
    written at the value the model defaults it to. Anything else -- a lost
    controller name, a changed size -- is data loss and fails here.
    """
    import yaml

    before = yaml.safe_load((CONFIGS / f"{stem}.yaml").read_text())
    out = tmp_path / "again.yaml"
    YAMLSerializer().save(YAMLSerializer().load(CONFIGS / f"{stem}.yaml"), out)
    after = yaml.safe_load(out.read_text())

    defaults = _model_defaults()
    for path, old, new in _differences(_upgrade(before), after):
        field = path[-1]
        if old is _ABSENT and new in defaults.get(field, ()):
            continue  # a field 1.1.9 did not have, at its default
        raise AssertionError(
            f"{'.'.join(path)}: {old!r} became {new!r}, which the rename table "
            f"does not account for"
        )


def test_legacy_field_values_are_understood():
    """Spot-check the 1.1.9 vocabulary that later phases must keep accepting."""
    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")
    assert vm.cpu.count == 8
    assert vm.memory.mb == 16384
    assert len(vm.storage) == 3
    formats = {d.format for d in vm.storage}
    assert formats == {DiskFormat.VDI, DiskFormat.VMDK, DiskFormat.VHD}
    assert Allocation.THICK in {d.allocation for d in vm.storage}
    assert BusType.SAS in {sc.bus for sc in vm.storage_controllers}
    # The 1.1.9 default that later phases must treat as "unset" (F-01/M-06).
    assert all(d.controller for d in vm.storage)


def test_legacy_network_vocabulary_is_understood():
    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multinic.yaml")
    assert {n.network_type for n in vm.networks} == {
        NetworkType.BRIDGED,
        NetworkType.HOSTONLY,
        NetworkType.INTERNAL,
        NetworkType.NATNETWORK,
    }
    # A 1.1.x file names the chipset the way its hypervisor does; the model is
    # the card, and both spellings of it resolve to the same one (A-10).
    from vmctl.core.platform import NicModel

    assert any(n.model is NicModel.VIRTIO for n in vm.networks)


# ---------------------------------------------------------------------------
# The other half of compatibility: code, not files
#
# Ground rule 2 covers what people wrote against vmctl as well as what they
# exported from it, so the 1.1.x names keep working as attributes and as
# constructor keywords. Tested on purpose here rather than incidentally.
# ---------------------------------------------------------------------------


def test_the_old_class_names_still_import():
    from vmctl.core.vmconfig import DiskConfig, StorageController, StorageControllerConfig
    from vmctl.core.vmconfig import StorageDevice

    assert DiskConfig is StorageDevice
    assert StorageControllerConfig is StorageController


def test_the_old_enum_names_are_the_new_ones():
    """Pure renames, so the members are the same objects and comparisons hold."""
    from vmctl.core.devices import Allocation, BusType, DeviceKind, DiskType, DiskVariant
    from vmctl.core.devices import StorageControllerType

    assert DiskVariant.THIN is Allocation.THIN
    assert StorageControllerType.SATA is BusType.SATA
    # DiskType is the enum that was split, so it is a shim onto DeviceKind.
    assert DiskType.DVD is DeviceKind.CDROM
    assert DiskType.HDD is DeviceKind.DISK
    assert DiskType("ssd") is DeviceKind.DISK


def test_the_old_device_keywords_still_construct():
    from vmctl.core.devices import Allocation, BusType, DeviceKind
    from vmctl.core.vmconfig import StorageDevice

    device = StorageDevice(
        name="d",
        type=DeviceKind.CDROM,
        variant=Allocation.THICK,
        controller=BusType.IDE,
        controller_name="IDE Controller",
        port=1,
        device=1,
    )
    assert device.kind is DeviceKind.CDROM
    assert device.allocation is Allocation.THICK
    # `controller` is the one keyword whose meaning changed rather than its name:
    # a BusType can only ever have meant the bus.
    assert device.bus is BusType.IDE
    assert device.controller == "IDE Controller"
    assert (device.slot, device.unit) == (1, 1)


def test_the_old_device_attributes_still_read_and_write():
    from vmctl.core.devices import DeviceKind
    from vmctl.core.vmconfig import StorageDevice

    device = StorageDevice(name="d")
    device.port = 3
    device.type = DeviceKind.FLOPPY
    assert (device.slot, device.kind) == (3, DeviceKind.FLOPPY)
    assert device.port == 3 and device.type is DeviceKind.FLOPPY


def test_a_controllers_old_name_keyword_is_its_native_name():
    from vmctl.core.devices import BusType
    from vmctl.core.vmconfig import StorageController

    controller = StorageController(name="SATA Controller", controller_type=BusType.SATA)
    assert controller.native_name == "SATA Controller"
    assert controller.bus is BusType.SATA
    # The logical id is derived, and `name` still reads back what a provider calls it.
    assert controller.id == "sata0"
    assert controller.name == "SATA Controller"


def test_a_controller_with_no_native_name_reads_back_its_id():
    from vmctl.core.vmconfig import StorageController

    assert StorageController(id="nvme0").name == "nvme0"


def test_the_vm_still_takes_and_exposes_disks():
    from vmctl.core.vmconfig import BootConfig, CPUConfig, FirmwareConfig, MemoryConfig
    from vmctl.core.vmconfig import StorageDevice, VMConfig

    vm = VMConfig(
        name="v",
        cpu=CPUConfig(),
        memory=MemoryConfig(),
        firmware=FirmwareConfig(),
        disks=[StorageDevice(name="root")],
        networks=[],
        boot=BootConfig(),
        storage_controllers=[],
    )
    assert vm.storage[0].name == "root"
    assert vm.disks is vm.storage
    vm.disks = [StorageDevice(name="other")]
    assert vm.storage[0].name == "other"


def test_giving_a_field_both_names_is_refused_rather_than_guessed():
    """Only one of the two can be honoured, so the file is wrong, not ambiguous."""
    with pytest.raises(ValidationError, match="both 'port' and 'slot'"):
        VMConfig.from_dict({"name": "v", "storage": [{"name": "d", "port": 0, "slot": 1}]})


def test_a_legacy_controller_value_that_is_not_a_bus_is_reported():
    """`controller:` named a bus in 1.1.x and names a controller now.

    The value tells them apart -- a bus is spelled like the enum -- so a typo in
    the old position reads as a controller nothing declares. That cannot be an
    error, because naming an undeclared controller is how "just put it on SATA"
    has always been written (F-01), so it is a warning that names both readings.
    """
    from vmctl.validators.vm_validator import VMValidator
    from vmctl.providers.virtualbox.capabilities import VirtualBoxCapabilities

    vm = VMConfig.from_dict({"name": "v", "disks": [{"name": "d", "controller": "fibrechannel"}]})
    assert vm.storage[0].controller == "fibrechannel"
    warnings = VMValidator(VirtualBoxCapabilities.get()).validate(vm)
    assert any("fibrechannel" in w and "nor a bus" in w for w in warnings)


def test_a_1_1_x_ostype_still_loads_and_still_works():
    """`ostype: Ubuntu_64` is a VirtualBox id, which A-05 keeps as a passthrough --
    the config was written against a tool that only had VirtualBox in it."""
    from vmctl.providers.virtualbox.tables import GuestOSCodec

    vm = VMConfig.from_dict({"name": "v", "ostype": "Ubuntu_64"})
    assert vm.guest_os == "Ubuntu_64"
    assert vm.ostype == "Ubuntu_64"  # the attribute alias reads it back
    assert GuestOSCodec().dump(vm.guest_os) == "Ubuntu_64"


def test_a_1_1_x_chipset_name_loads_as_the_card_it_is():
    """`adapter_type: "82540EM"` was VirtualBox's id for the Intel PRO/1000 MT
    Desktop. The model names the card, so both spellings mean the same thing."""
    from vmctl.core.platform import NicModel

    for spelling in ("82540EM", "e1000", "Am79C973", "virtio"):
        vm = VMConfig.from_dict({"name": "v", "networks": [{"adapter_type": spelling}]})
        assert isinstance(vm.networks[0].model, NicModel), spelling
    assert (
        VMConfig.from_dict({"name": "v", "networks": [{"adapter_type": "82545EM"}]})
        .networks[0]
        .model
        is NicModel.E1000
    )


def test_old_code_can_still_pass_a_chipset_string():
    from vmctl.core.platform import NicModel
    from vmctl.core.vmconfig import NetworkConfig

    assert NetworkConfig(adapter_type="82540EM").model is NicModel.E1000
    assert NetworkConfig(adapter_type="virtio").adapter_type is NicModel.VIRTIO


def test_a_1_1_x_config_creates_a_qemu_vm(tmp_path):
    """The point of the whole phase, stated as a test: a file written for a
    VirtualBox-only vmctl describes a VM a third hypervisor can create. Nothing in
    it mentions QEMU, and nothing in it had to change."""
    from vmctl.core.translate import Policy
    from vmctl.providers.qemu.emitter import QemuEmitter

    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")
    plan = QemuEmitter(vm.name, policy=Policy.NEAREST).emit_create_vm(vm)
    argv = [step.argv for step in plan if step.argv and step.argv[0] == "qemu-img"]
    assert argv, "the disks should be created"
    written = [step for step in plan if step.content][0]
    assert "exec " in written.content and "-device" in written.content


def test_a_1_1_x_config_creates_a_vmware_vm():
    """The fourth hypervisor, from the same 1.1.9 file. Its VDI disks are not
    something VMware can write, so `nearest` makes them VMDK and says so -- which is
    the difference between a provider that translates and one that pretends."""
    from vmctl.core.translate import Policy
    from vmctl.providers.vmware.emitter import VMwareEmitter

    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")
    emitter = VMwareEmitter(vm.name, tools_dir="", policy=Policy.NEAREST)
    plan = emitter.emit_create_vm(vm)
    assert [s for s in plan if s.content], "a .vmx should be written"
    assert any("vdi is not supported" in line for line in plan.warnings)


# ---------------------------------------------------------------------------
# schema_version (E-14)
# ---------------------------------------------------------------------------


def test_a_file_that_does_not_say_is_taken_to_be_current():
    """Which is what it almost always is -- and every 1.1.9 file in these fixtures says
    nothing, so the alternative would be refusing all of them."""
    from vmctl.core.vmconfig import SCHEMA_VERSION

    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")

    assert vm.schema_version == SCHEMA_VERSION


def test_what_vmctl_writes_says_which_format_it_is(tmp_path):
    from vmctl.core.vmconfig import SCHEMA_VERSION

    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")
    path = tmp_path / "out.yaml"
    YAMLSerializer().save(vm, path)

    assert f"schema_version: {SCHEMA_VERSION}" in path.read_text()
    # ...and reading it back is the same VM, which is what the field is for.
    assert YAMLSerializer().load(path).name == vm.name


def test_a_file_from_the_future_is_refused_by_saying_so(tmp_path):
    """The useful case. Its fields are not unknown, they are from a later vmctl, and
    "Unknown field 'x'" about whichever one comes first is a worse answer."""
    path = tmp_path / "future.yaml"
    path.write_text("schema_version: 99\nname: from-the-future\n")

    with pytest.raises(ValidationError) as raised:
        YAMLSerializer().load(path)

    assert "understands up to" in str(raised.value)
    assert "upgrade vmctl" in (raised.value.recovery_hint or "")


def test_a_version_that_is_not_a_number_is_refused(tmp_path):
    path = tmp_path / "odd.yaml"
    path.write_text("schema_version: tomorrow\nname: x\n")

    with pytest.raises(ValidationError, match="must be a number"):
        YAMLSerializer().load(path)


def test_declaring_the_1_1_x_format_still_loads_1_1_x_names(tmp_path):
    """The number does not gate the loader: old names are translated by key, so a file
    does not have to declare its age to be read -- and one that does is still read."""
    path = tmp_path / "old.yaml"
    path.write_text(
        "schema_version: 1\nname: old\nostype: Ubuntu_64\n"
        "disks:\n  - name: system\n    size_mb: 1024\n    type: hdd\n"
    )

    vm = YAMLSerializer().load(path)

    assert vm.schema_version == 1
    assert vm.storage[0].name == "system"
    assert vm.guest_os == "Ubuntu_64"


def test_the_format_version_is_not_drift():
    """It describes the file, not the VM: no hypervisor has an opinion about it, so a
    comparison can only ever report it as noise (E-01)."""
    from vmctl.core.diff import diff

    live = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")
    desired = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")
    desired.schema_version = 1

    assert diff(live, desired) == []
