"""The generated documentation tables (E-18).

Two tables in this project drifted when they were written by hand -- what a config file
may contain, and what each hypervisor supports -- so they are generated from the code
that already states both. These tests are the reason that keeps working: they fail when
the committed copies stop matching what the code would produce, the same arrangement
that guards ``vmctl.schema.json``.
"""

from pathlib import Path

import pytest

import vmctl.providers  # noqa: F401  (registers the built-in providers)
from vmctl.core import docgen

DOCS = Path(__file__).parent.parent / "docs"

#: What the script writes, and what renders it.
GENERATED = {
    "features.md": docgen.field_reference,
    "providers.md": docgen.provider_matrix,
    "commands.md": docgen.command_reference,
}


@pytest.mark.parametrize("name", sorted(GENERATED))
def test_the_committed_copy_is_current(name):
    """Run `python scripts/generate-docs.py` when this fails."""
    rendered = GENERATED[name]()
    if not rendered.endswith("\n"):
        rendered += "\n"

    assert (
        DOCS / name
    ).read_text() == rendered, (
        f"docs/{name} is out of date -- run 'python scripts/generate-docs.py'"
    )


@pytest.mark.parametrize("name", sorted(GENERATED))
def test_every_generated_file_says_it_is_generated(name):
    """The first instinct on finding a wrong table is to edit the table."""
    text = (DOCS / name).read_text()
    assert "Generated by scripts/generate-docs.py" in text
    assert "Do not edit" in text


# ---------------------------------------------------------------------------
# The field reference
# ---------------------------------------------------------------------------


def test_every_field_of_every_section_is_listed():
    """The failure this replaces: `docs/features.md` still described `ostype` as a
    VirtualBox identifier and had no `storage`, no `guest_os` and no `port_forwards`,
    long after the model had them."""
    from dataclasses import fields

    text = docgen.field_reference()

    for _, dataclass_ in docgen.SECTIONS:
        for spec in fields(dataclass_):
            assert f"`{spec.name}`" in text, f"{dataclass_.__name__}.{spec.name} is missing"


def test_every_field_is_explained():
    """A table of names and types explains nothing; the model already has the sentences."""
    from dataclasses import fields

    from vmctl.core.schema import field_doc

    undocumented = [
        f"{dc.__name__}.{spec.name}"
        for _, dc in docgen.SECTIONS
        for spec in fields(dc)
        if not field_doc(dc, spec.name)
    ]

    assert not undocumented, undocumented


def test_the_1_1_x_names_are_shown_as_still_accepted():
    text = docgen.field_reference()
    assert "`disks`" in text and "`ostype`" in text and "`adapter_type`" in text


def test_the_vocabularies_come_from_the_enums():
    """So a new bus or format appears without anyone editing prose."""
    from vmctl.core.devices import BusType

    text = docgen.field_reference()
    for bus in BusType:
        assert f"`{bus.value}`" in text


def test_the_format_version_is_stated():
    from vmctl.core.vmconfig import SCHEMA_VERSION

    assert f"**{SCHEMA_VERSION}**" in docgen.field_reference()


# ---------------------------------------------------------------------------
# The provider matrix
# ---------------------------------------------------------------------------


def test_every_provider_has_a_section():
    from vmctl.core import registry

    text = docgen.provider_matrix()
    for name in registry.names():
        assert f"## {name}" in text


def test_each_provider_says_where_its_numbers_came_from():
    """The most important line in the file: a measured limit and a remembered one look
    identical in a table."""
    text = docgen.provider_matrix()
    assert text.count("**Measured on:**") >= 4


def test_the_matrix_states_what_attaches_to_what():
    text = docgen.provider_matrix()
    assert "### Buses, and what attaches to them" in text
    assert "| disk | cdrom | floppy |" in text


def test_the_matrix_covers_the_newer_capabilities():
    text = docgen.provider_matrix()
    assert "| Snapshots |" in text and "| NAT port forwards |" in text
    # VMware genuinely cannot forward a port, and the table has to say so rather than
    # leaving the reader to assume four identical hypervisors.
    assert "cannot be expressed here" in text


def test_rendering_is_deterministic():
    """Otherwise the "is it current?" test above would fail at random."""
    assert docgen.provider_matrix() == docgen.provider_matrix()
    assert docgen.field_reference() == docgen.field_reference()


# ---------------------------------------------------------------------------
# The command list
# ---------------------------------------------------------------------------


def test_every_command_is_listed():
    """Asked of Click rather than written down, so a new command cannot be forgotten."""
    from vmctl.cli.main import cli

    text = docgen.command_reference()
    for name in cli.commands:
        assert f"`vmctl {name}`" in text


def test_a_group_lists_its_subcommands():
    text = docgen.command_reference()
    assert "`vmctl snapshot take`" in text
    assert "`vmctl batch create`" in text


def test_a_summary_is_not_truncated_to_the_terminal_width():
    """Which is what reading `--help` output gave: "Change the CPU, memory, ... of an..."."""
    assert "of an existing VM." in docgen.command_reference()
