"""Backward-compatibility guard (PLAN.md ground rule 2).

Config files produced by v1.1.9 must keep loading in every later version. These
fixtures were generated by the shipped 1.1.9 code and must never be regenerated
— that is the whole point. When a later phase renames or reshapes a field, the
loader gains an alias and these tests keep passing.
"""

from pathlib import Path

import pytest

from vmctl.core.vmconfig import (
    DiskFormat,
    Allocation,
    NetworkType,
    BusType,
    VMConfig,
)
from vmctl.serializers.json_serializer import JSONSerializer
from vmctl.serializers.yaml_serializer import YAMLSerializer

CONFIGS = Path(__file__).parent / "fixtures" / "configs"
LEGACY = ["v1_1_9_multidisk", "v1_1_9_multinic"]


@pytest.mark.parametrize("stem", LEGACY)
def test_legacy_yaml_still_loads(stem):
    vm = YAMLSerializer().load(CONFIGS / f"{stem}.yaml")
    assert isinstance(vm, VMConfig)
    assert vm.name
    assert vm.cpu.count >= 1


@pytest.mark.parametrize("stem", LEGACY)
def test_legacy_json_still_loads(stem):
    vm = JSONSerializer().load(CONFIGS / f"{stem}.json")
    assert isinstance(vm, VMConfig)
    assert vm.name


@pytest.mark.parametrize("stem", LEGACY)
def test_legacy_yaml_and_json_describe_the_same_vm(stem):
    y = YAMLSerializer().load(CONFIGS / f"{stem}.yaml")
    j = JSONSerializer().load(CONFIGS / f"{stem}.json")
    assert YAMLSerializer().to_dict(y) == JSONSerializer().to_dict(j)


@pytest.mark.parametrize("stem", LEGACY)
def test_saving_twice_produces_the_same_file(stem, tmp_path):
    """Load/save is a fixed point, so editing one setting shows one line in the diff.

    This is the no-churn guarantee in the form that survives a rename: within a
    version, saving what was loaded changes nothing.
    """
    vm = YAMLSerializer().load(CONFIGS / f"{stem}.yaml")
    first = tmp_path / "first.yaml"
    YAMLSerializer().save(vm, first)
    second = tmp_path / "second.yaml"
    YAMLSerializer().save(YAMLSerializer().load(first), second)
    assert second.read_text() == first.read_text()


#: Values the 1.1.x vocabulary spelled differently, and what they became (M-01).
#: `ssd` is the one that is not a rename: it splits into a kind and a flag, so the
#: flag turns up as an added key, which the rule below already allows.
RENAMED_VALUES = {"type": {"hdd": "disk", "ssd": "disk", "dvd": "cdrom"}}


def _model_defaults():
    """Every default the model declares, by field name.

    Used to recognise a key that a 1.1.9 file simply did not have yet, as opposed
    to one whose value changed.
    """
    from dataclasses import MISSING, fields

    from vmctl.core import vmconfig as m

    out = {}
    for name in dir(m):
        dc = getattr(m, name)
        if not (isinstance(dc, type) and hasattr(dc, "__dataclass_fields__")):
            continue
        for f in fields(dc):
            if f.default is not MISSING:
                value = f.default
                out.setdefault(f.name, set()).add(value.value if hasattr(value, "value") else value)
    return out


def _differences(before, after, path=()):
    """Yield ``(path, old, new)`` for every leaf that is not identical.

    A key present on one side only yields ``_ABSENT`` for the other.
    """
    if isinstance(before, dict) and isinstance(after, dict):
        for key in sorted(set(before) | set(after)):
            yield from _differences(
                before.get(key, _ABSENT), after.get(key, _ABSENT), path + (str(key),)
            )
    elif isinstance(before, list) and isinstance(after, list) and len(before) == len(after):
        for i, (b, a) in enumerate(zip(before, after)):
            yield from _differences(b, a, path + (str(i),))
    elif before != after:
        yield path, before, after


_ABSENT = object()


@pytest.mark.parametrize("stem", LEGACY)
def test_upgrading_a_legacy_file_only_renames_what_the_plan_says(stem, tmp_path):
    """Saving a 1.1.9 file with today's vmctl may rename vocabulary, nothing else.

    Ground rule 2 promises old files keep loading; it does not promise the words
    never improve. `type: hdd` becomes `type: disk` because `hdd` and `ssd` were
    never two kinds of device (M-01). So the test states the narrower promise:
    every difference is either a documented rename, or a field the old version
    did not have, written at the value the model defaults it to. Anything else --
    a lost controller name, a changed size -- is data loss and fails here.
    """
    import yaml

    before = yaml.safe_load((CONFIGS / f"{stem}.yaml").read_text())
    out = tmp_path / "again.yaml"
    YAMLSerializer().save(YAMLSerializer().load(CONFIGS / f"{stem}.yaml"), out)
    after = yaml.safe_load(out.read_text())

    defaults = _model_defaults()
    for path, old, new in _differences(before, after):
        field = path[-1]
        if old is _ABSENT and new in defaults.get(field, ()):
            continue  # a field 1.1.9 did not have, at its default
        if RENAMED_VALUES.get(field, {}).get(old) == new:
            continue  # a documented rename
        raise AssertionError(f"{'.'.join(path)}: {old!r} became {new!r}, which is not a rename")


def test_legacy_field_values_are_understood():
    """Spot-check the 1.1.9 vocabulary that later phases must keep accepting."""
    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multidisk.yaml")
    assert vm.cpu.count == 8
    assert vm.memory.mb == 16384
    assert len(vm.disks) == 3
    formats = {d.format for d in vm.disks}
    assert formats == {DiskFormat.VDI, DiskFormat.VMDK, DiskFormat.VHD}
    assert Allocation.THICK in {d.variant for d in vm.disks}
    assert BusType.SAS in {sc.controller_type for sc in vm.storage_controllers}
    # The 1.1.9 default that later phases must treat as "unset" (F-01/M-06).
    assert all(d.controller_name for d in vm.disks)


def test_legacy_network_vocabulary_is_understood():
    vm = YAMLSerializer().load(CONFIGS / "v1_1_9_multinic.yaml")
    assert {n.network_type for n in vm.networks} == {
        NetworkType.BRIDGED,
        NetworkType.HOSTONLY,
        NetworkType.INTERNAL,
        NetworkType.NATNETWORK,
    }
    assert any(n.adapter_type == "virtio" for n in vm.networks)
