"""
Documentation rendered from the code (E-18).

Two tables in this project have drifted before and will again if they are written by
hand: **what a config file may contain** and **what each hypervisor supports**. Both
are already stated precisely -- the first by the dataclasses, the second by each
provider's capability declaration -- so the documentation is generated from those,
the way the JSON Schema is (E-06).

``docs/features.md`` was the proof that this is needed: it still described ``ostype``
as "VirtualBox OS type identifier" and had no ``storage``, no ``guest_os`` and no
``port_forwards``, months after the model gained them. A table nobody can forget to
update is the only kind worth publishing.

Markdown, because both Sphinx trees accept it (``myst_parser``) and GitHub renders it
directly -- so one rendering serves the repository, the English documentation and the
Arabic one, rather than three that agree by luck.
"""

from dataclasses import MISSING, fields, is_dataclass
from enum import Enum
from typing import Any, Dict, List, Optional, Union, get_args, get_origin, get_type_hints

from . import registry
from .capabilities import Capabilities
from .devices import Allocation, BusType, DeviceKind, DiskFormat
from .platform import Arch, NicModel
from .schema import LEGACY_BY_CLASS, field_doc
from .vmconfig import (
    SCHEMA_VERSION,
    BootConfig,
    CPUConfig,
    FirmwareConfig,
    FirmwareType,
    MemoryConfig,
    NetworkConfig,
    NetworkType,
    PortForward,
    StorageController,
    StorageDevice,
    VMConfig,
)

#: The order the field reference presents the model in: the VM first, then the parts of
#: it, in the order someone writing a config meets them.
SECTIONS = [
    ("The VM", VMConfig),
    ("cpu", CPUConfig),
    ("memory", MemoryConfig),
    ("firmware", FirmwareConfig),
    ("boot", BootConfig),
    ("storage (each device)", StorageDevice),
    ("storage_controllers (each controller)", StorageController),
    ("networks (each adapter)", NetworkConfig),
    ("port_forwards (each rule)", PortForward),
]

#: Vocabularies worth listing in full, because a value outside one is refused.
VOCABULARIES = [
    ("Device kinds", DeviceKind),
    ("Buses", BusType),
    ("Disk formats", DiskFormat),
    ("Allocation", Allocation),
    ("Firmware", FirmwareType),
    ("Network modes", NetworkType),
    ("Network cards", NicModel),
    ("Architectures", Arch),
]

#: Said at the top of every generated file, because the first instinct on finding a
#: wrong table is to edit the table.
BANNER = (
    "<!-- Generated by scripts/generate-docs.py from vmctl's own model and the\n"
    "     providers' capability declarations. Do not edit: run the script instead.\n"
    "     CI checks that the committed copy is current. -->\n"
)


def field_reference() -> str:
    """Return the configuration reference as Markdown."""
    out: List[str] = [
        BANNER,
        "# Configuration reference",
        "",
        "Every field a vmctl configuration file may contain, generated from the model "
        "that reads it. The 1.1.x names in the last column are still accepted.",
        "",
        f"Current configuration format: **{SCHEMA_VERSION}** "
        "(`schema_version:`; a file that omits it is read as this one).",
        "",
    ]
    for title, dc in SECTIONS:
        out += [f"## {title}", ""]
        summary = (dc.__doc__ or "").strip().splitlines()
        if summary and not summary[0].startswith("Attributes"):
            out += [summary[0].strip(), ""]
        out += _field_table(dc)
        out += [""]

    out += ["## Values", ""]
    for title, enum in VOCABULARIES:
        values = ", ".join(f"`{member.value}`" for member in enum)
        out += [f"- **{title}**: {values}"]
    out += [""]
    return "\n".join(out)


def _field_table(dc: type) -> List[str]:
    """Return one dataclass as a Markdown table."""
    hints = get_type_hints(dc)
    aliases = {new: old for old, new in LEGACY_BY_CLASS.get(dc.__name__, {}).items()}
    rows = ["| Field | Type | Default | Was called | Description |", "|---|---|---|---|---|"]
    for spec in fields(dc):
        rows.append(
            "| `{name}` | {type} | {default} | {alias} | {doc} |".format(
                name=spec.name,
                type=_type_name(hints.get(spec.name, Any)),
                default=_default(spec),
                alias=f"`{aliases[spec.name]}`" if spec.name in aliases else "",
                doc=_one_line(field_doc(dc, spec.name)),
            )
        )
    return rows


def _type_name(tp: Any) -> str:
    """Return a type as a person would say it, not as ``typing`` prints it."""
    origin = get_origin(tp)
    if origin is Union:
        inner = [arg for arg in get_args(tp) if arg is not type(None)]
        return f"{_type_name(inner[0])} or empty" if inner else "empty"
    if origin in (list, List):
        args = get_args(tp)
        return f"list of {_type_name(args[0])}" if args else "list"
    if origin in (dict, Dict):
        return "mapping"
    if isinstance(tp, type) and issubclass(tp, Enum):
        return "one of " + " / ".join(f"`{member.value}`" for member in tp)
    if isinstance(tp, type) and is_dataclass(tp):
        return tp.__name__
    return {bool: "yes/no", int: "number", str: "text", float: "number"}.get(tp, "value")


def _default(spec: Any) -> str:
    """Return a field's default, or what it means to have none."""
    if spec.default is not MISSING:
        value = spec.default
        if isinstance(value, Enum):
            return f"`{value.value}`"
        if value is None or value == "":
            return "empty"
        if isinstance(value, bool):
            return f"`{str(value).lower()}`"
        return f"`{value}`"
    if spec.default_factory is not MISSING:  # type: ignore[misc]
        made = spec.default_factory()
        return "empty" if not made else f"`{made}`"
    return "**required**"


def _one_line(text: Optional[str]) -> str:
    """Return a description that fits in a table cell."""
    if not text:
        return ""
    cleaned = " ".join(text.split()).replace("|", "\\|")
    cleaned = cleaned.replace("``", "`")
    # A description written for a docstring can be a paragraph; a table wants the
    # sentence that says what the field is, with the reasoning left in the source.
    for end in (". ", "; "):
        if end in cleaned and len(cleaned) > 160:
            cleaned = cleaned.split(end)[0] + "."
            break
    return cleaned


def provider_matrix() -> str:
    """Return what each registered provider supports, as Markdown."""
    out: List[str] = [
        BANNER,
        "# What each hypervisor supports",
        "",
        "Generated from each provider's capability declaration -- the same one the "
        "validator and the translator read, so what is listed here is what vmctl will "
        "accept. Each provider states where its numbers came from; that line is the "
        "most important one in this file, because a measured limit and a remembered "
        "one look identical in a table.",
        "",
        "Ask a specific host directly with `vmctl -p <provider> capabilities`, which "
        "also probes what only the machine can answer (bridges, machine types).",
        "",
    ]
    for name in registry.names():
        try:
            caps = registry.provider_class(name)().capabilities
        except Exception as exc:  # pragma: no cover - a provider that cannot construct
            out += [f"## {name}", "", f"*could not be described: {exc}*", ""]
            continue
        out += _provider_section(name, caps)
    return "\n".join(out)


def _provider_section(name: str, caps: Capabilities) -> List[str]:
    """Return one provider's section."""
    out = [f"## {name}", ""]
    if caps.evidence:
        out += [f"**Measured on:** {_one_line(caps.evidence)}", ""]

    out += [
        "### Disk formats",
        "",
        "| Format | Create | Attach | Extensions |",
        "|---|---|---|---|",
    ]
    for fmt, spec in sorted(caps.formats.items(), key=lambda pair: pair[0].value):
        native = " (native)" if fmt is caps.native_format else ""
        out.append(
            f"| `{fmt.value}`{native} | {_mark(spec.support.creatable)} | "
            f"{_mark(spec.support.usable)} | {', '.join(spec.extensions)} |"
        )

    kinds = [DeviceKind.DISK, DeviceKind.CDROM, DeviceKind.FLOPPY]
    out += [
        "",
        "### Buses, and what attaches to them",
        "",
        "| Bus | " + " | ".join(kind.value for kind in kinds) + " | Ports | Bootable |",
        "|---|" + "---|" * (len(kinds) + 2),
    ]
    for bus, bus_spec in sorted(caps.buses.items(), key=lambda pair: pair[0].value):
        marks = " | ".join(_mark(caps.can_attach(kind, bus)) for kind in kinds)
        fixed = bus_spec.fixed_port_count
        ports = f"{fixed}" if fixed else f"{bus_spec.min_ports}-{bus_spec.max_ports}"
        if bus_spec.units_per_port > 1:
            ports += f" x {bus_spec.units_per_port}"
        idiomatic = [kind.value for kind, other in caps.native_buses.items() if other is bus]
        suffix = f" (native for {', '.join(idiomatic)})" if idiomatic else ""
        out.append(f"| `{bus.value}`{suffix} | {marks} | {ports} | {_mark(bus_spec.bootable)} |")

    out += [
        "",
        "### The rest",
        "",
        "| | |",
        "|---|---|",
        f"| CPUs | up to {caps.max_cpus} |",
        f"| Memory | up to {caps.max_memory_mb} MB |",
        f"| Devices | up to {caps.max_disks} |",
        f"| Network adapters | up to {caps.max_network_adapters} |",
        "| Firmware | "
        + ", ".join(
            f"`{firmware.value}` ({support.value})"
            for firmware, support in sorted(caps.firmware.items(), key=lambda p: p[0].value)
        )
        + " |",
        "| Network modes | "
        + (", ".join(f"`{mode}`" for mode in caps.supported_network_types) or "-")
        + " |",
        "| Network cards | "
        + (
            ", ".join(
                f"`{model.value}`"
                for model in sorted(caps.nic_models, key=lambda model: model.value)
            )
            or "-"
        )
        + " |",
        f"| CPU topology | {_mark(caps.cpu_topology)} |",
        f"| Machine types | {', '.join(caps.machine_types[:6]) or 'not a setting here'} |",
        f"| TPM | {_mark(caps.supports_tpm)} |",
        f"| Snapshots | {_snapshots(caps)} |",
        f"| NAT port forwards | {_forwards(caps)} |",
        "",
    ]
    return out


def _snapshots(caps: Capabilities) -> str:
    if not caps.snapshots.usable:
        return "no"
    where = (
        ", ".join(sorted(f"`{fmt.value}`" for fmt in caps.snapshot_formats))
        if caps.snapshot_formats
        else "any attachable format"
    )
    return f"yes, on {where}; descriptions {_mark(caps.snapshot_descriptions)}"


def _forwards(caps: Capabilities) -> str:
    if not caps.port_forwards.usable:
        return "no -- cannot be expressed here"
    return "yes" + (", rules are named" if caps.port_forward_names else "")


def _mark(value: bool) -> str:
    """Return a table cell for a yes/no."""
    return "yes" if value else "-"


def command_reference() -> str:
    """Return the command list, asked of the CLI itself.

    Asked rather than written down, so a new command appears here without anyone
    remembering to add it -- and asked through Click's own objects rather than by
    running ``--help``, whose listing truncates a long summary to the terminal width.
    The per-command reference with every option is the Sphinx tree's ``sphinx-click``
    page; this is the index a reader wants in the repository.
    """
    from ..cli.main import cli

    out = [BANNER, "# Commands", ""]
    for name in sorted(cli.commands):
        command = cli.commands[name]
        summary = (command.help or "").strip().splitlines()
        first = summary[0].strip() if summary else ""
        line = f"- **`vmctl {name}`** -- {first}" if first else f"- **`vmctl {name}`**"
        out.append(line)
        # A group's subcommands are commands in their own right to anyone reading a
        # list of what vmctl can do.
        children = getattr(command, "commands", {})
        for sub_name in sorted(children):
            subcommand = children[sub_name]
            sub_summary = (subcommand.help or "").strip().splitlines()
            sub_first = sub_summary[0].strip() if sub_summary else ""
            out.append(f"  - `vmctl {name} {sub_name}` -- {sub_first}")
    out += ["", "Run `vmctl <command> --help` for the options of any one of them.", ""]
    return "\n".join(out)
