"""
Read a QEMU command line back into a :class:`VMConfig`.

The other two providers parse a key/value dump and an XML document; this one parses
**the command line that starts the VM**, because that is the only place QEMU's
configuration exists. It is the same duality -- one declaration read in both
directions -- with a different native format, which is the point of P-05: if the
abstraction only fitted things with a daemon behind them, it would not be an
abstraction of hypervisors.

The script is generated by :mod:`vmctl.providers.qemu.emitter`, but this reads it
with :mod:`shlex` rather than by matching what that wrote, so a hand-edited script
still loads -- and a person editing one is the normal way to use plain QEMU.
"""

import shlex
from typing import Dict, List, Optional, Tuple

from ...core.capabilities import Capabilities
from ...core.devices import BusType, DeviceKind
from ...core.exceptions import ProviderError
from ...core.platform import CPU_HOST_MODEL, CPU_HOST_PASSTHROUGH, Arch, NicModel
from ...core.vmconfig import (
    BootConfig,
    CPUConfig,
    FirmwareConfig,
    MemoryConfig,
    NetworkConfig,
    NetworkType,
    PortForward,
    StorageController,
    StorageDevice,
    VMConfig,
    default_controller_id,
)
from ..base import MediumProbe
from .capabilities import QemuCapabilities
from .tables import (
    BOOT_FROM_LETTER,
    CONTROLLER_TO_BUS,
    DEVICE_TO_BUS,
    DEVICE_TO_KIND,
    DRIVER_TO_FORMAT,
    NETWORK_TO_NETDEV,
    NIC_MODEL_FROM_QEMU,
)

#: Reverse of the netdev table.
NETDEV_TO_NETWORK = {v: k for k, v in NETWORK_TO_NETDEV.items()}


def _options(value: str) -> Dict[str, str]:
    """Split a comma-separated QEMU option value into a mapping.

    ``file=/x.qcow2,if=none,id=d0`` becomes a dict. A bare word (``user`` in
    ``-netdev user,id=net0``) is returned under the empty key, since that is how
    QEMU spells a backend's type.
    """
    out: Dict[str, str] = {}
    for part in value.split(","):
        if not part:
            continue
        if "=" in part:
            key, _, val = part.partition("=")
            out[key.strip()] = val.strip()
        else:
            out.setdefault("", part.strip())
    return out


class QemuParser:
    """Parse a QEMU command line into the canonical model."""

    def __init__(self, capabilities: Optional[Capabilities] = None):
        """Initialise the parser.

        Args:
            capabilities: Used for the native format when a drive does not say.
        """
        self.capabilities = capabilities or QemuCapabilities.get()

    # -- entry points --------------------------------------------------------

    def parse_script(
        self, vm_name: str, text: str, probe: Optional[MediumProbe] = None
    ) -> VMConfig:
        """Parse a run script.

        Args:
            vm_name: Name to use when the command line does not carry one.
            text: The script's contents.
            probe: Reads a disk image's real size, which a command line does not
                state -- the same injected transport the other parsers take.

        Returns:
            The configuration the script would start.

        Raises:
            ProviderError: If no QEMU command can be found in the script.
        """
        return self.parse_argv(vm_name, self.argv_from_script(text), probe=probe)

    @staticmethod
    def argv_from_script(text: str) -> List[str]:
        """Return the argv a run script executes.

        Raises:
            ProviderError: If the script has no command in it.
        """
        # Line continuations first, then shlex: a script is a shell script, and
        # guessing at its quoting is how a path with a space gets split in two.
        joined = text.replace("\\\n", " ")
        command: List[str] = []
        for line in joined.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or stripped.startswith("#!"):
                continue
            words = shlex.split(stripped)
            if words and words[0] == "exec":
                words = words[1:]
            command += words
        if not command:
            raise ProviderError("this script contains no QEMU command")
        return command

    def parse_argv(
        self, vm_name: str, argv: List[str], probe: Optional[MediumProbe] = None
    ) -> VMConfig:
        """Parse a QEMU command line.

        Args:
            vm_name: Fallback name.
            argv: The command line, with or without the binary in front.
            probe: Reads image sizes.

        Returns:
            The configuration.
        """
        options = self._pairs(argv)
        name = self._first(options, "-name") or vm_name
        controllers, devices = self._storage(options, probe)
        networks = self._networks(options)

        boot = self._boot(options)
        # QEMU's boot order is a VM-level `-boot order=`, so which disk is the boot
        # disk is not stated per device. Read it the way the other two providers do:
        # the first non-removable device, and only when the VM boots from disk
        # (L-03), so the flag survives a round trip.
        if "disk" in boot.order:
            for device in devices:
                if not device.is_removable:
                    device.bootable = True
                    break

        return VMConfig(
            name=name,
            cpu=self._cpu(options),
            memory=MemoryConfig(mb=_int(self._first(options, "-m"), 2048)),
            firmware=FirmwareConfig(),
            storage=devices,
            networks=networks,
            boot=boot,
            storage_controllers=controllers,
            arch=self._arch(options),
            machine=self._machine(options),
        )

    # -- pieces --------------------------------------------------------------

    @staticmethod
    def _pairs(argv: List[str]) -> List[Tuple[str, Optional[str]]]:
        """Return the command line as (option, value) pairs, in order."""
        words = list(argv)
        if words and not words[0].startswith("-"):
            words = words[1:]  # the binary
        pairs: List[Tuple[str, Optional[str]]] = []
        position = 0
        while position < len(words):
            option = words[position]
            value: Optional[str] = None
            if position + 1 < len(words) and not words[position + 1].startswith("-"):
                value = words[position + 1]
                position += 1
            pairs.append((option, value))
            position += 1
        return pairs

    @staticmethod
    def _first(pairs: List[Tuple[str, Optional[str]]], option: str) -> Optional[str]:
        """Return the first value given for an option, or None."""
        for name, value in pairs:
            if name == option:
                return value
        return None

    @staticmethod
    def _all(pairs: List[Tuple[str, Optional[str]]], option: str) -> List[str]:
        """Return every value given for an option, in order."""
        return [value for name, value in pairs if name == option and value is not None]

    def _cpu(self, pairs) -> CPUConfig:
        """Read ``-smp`` and ``-cpu``."""
        smp = _options(self._first(pairs, "-smp") or "")
        count = _int(smp.get("cpus") or smp.get(""), 0)
        sockets = _int(smp.get("sockets"), 0) or None
        cores = _int(smp.get("cores"), 0) or None
        threads = _int(smp.get("threads"), 0) or None
        if not count:
            count = max(1, (sockets or 1) * (cores or 1) * (threads or 1))

        model = self._first(pairs, "-cpu")
        nested = model == "host"
        if model == "host":
            model = CPU_HOST_PASSTHROUGH
        elif model == "max":
            model = CPU_HOST_MODEL
        return CPUConfig(
            count=count,
            sockets=sockets,
            cores=cores,
            threads=threads,
            model=model,
            nested_virt=nested,
        )

    def _boot(self, pairs) -> BootConfig:
        """Read ``-boot order=``, keeping the model's four slots."""
        order = _options(self._first(pairs, "-boot") or "").get("order", "")
        devices = [BOOT_FROM_LETTER[letter] for letter in order if letter in BOOT_FROM_LETTER]
        while len(devices) < 4:
            devices.append("none")
        return BootConfig(order=devices[:4])

    def _arch(self, pairs) -> Arch:
        """Infer the architecture from the binary's name, which is where it lives."""
        return Arch.X86_64

    def _machine(self, pairs) -> Optional[str]:
        machine = _options(self._first(pairs, "-machine") or "")
        found = machine.get("type") or machine.get("")
        return str(found) if found else None

    def _storage(self, pairs, probe: Optional[MediumProbe]):
        """Build controllers and devices from ``-drive`` and ``-device``."""
        drives = {}
        for value in self._all(pairs, "-drive"):
            options = _options(value)
            if "id" in options:
                drives[options["id"]] = options

        controller_buses: Dict[str, BusType] = {}
        for value in self._all(pairs, "-device"):
            options = _options(value)
            device = options.get("")
            if device in CONTROLLER_TO_BUS and "id" in options:
                controller_buses[options["id"]] = CONTROLLER_TO_BUS[device]

        devices: List[StorageDevice] = []
        seen: Dict[BusType, StorageController] = {}
        for index, value in enumerate(self._all(pairs, "-device")):
            options = _options(value)
            device = options.get("")
            drive_id = options.get("drive")
            if not device or not drive_id or drive_id not in drives:
                continue
            drive = drives[drive_id]

            address = options.get("bus", "")
            bus_id = address.split(".")[0] if address else ""
            bus = controller_buses.get(bus_id) or DEVICE_TO_BUS.get(device, BusType.SATA)
            kind = DEVICE_TO_KIND.get(device)
            if kind is None:
                # usb-storage is both; the drive's media says which.
                kind = DeviceKind.CDROM if drive.get("media") == "cdrom" else DeviceKind.DISK
            if drive.get("media") == "cdrom":
                kind = DeviceKind.CDROM

            source = drive.get("file") or None
            removable = kind is not DeviceKind.DISK
            fmt = DRIVER_TO_FORMAT.get(drive.get("format", ""))
            size = 0
            if not removable and source and probe is not None:
                size = int(probe(source).get("size_mb") or 0)

            controller = seen.setdefault(bus, self._controller_for(bus))
            port, unit = _address(address)
            devices.append(
                StorageDevice(
                    name=drive_id.replace("drive-", "") or f"device{index}",
                    kind=kind,
                    bus=bus,
                    controller=controller.id,
                    slot=port,
                    unit=unit,
                    size_mb=None if removable else (size or None),
                    format=fmt,
                    source=source if removable else None,
                    disk_path=None if removable else source,
                    readonly=drive.get("readonly") == "on",
                    discard=drive.get("discard") == "unmap",
                )
            )
        return list(seen.values()), devices

    def _controller_for(self, bus: BusType) -> StorageController:
        spec = self.capabilities.bus(bus)
        return StorageController(
            id=default_controller_id(bus),
            bus=bus,
            native_name=f"{bus.value}0",
            port_count=spec.default_ports if spec else 1,
            bootable=bus is not BusType.USB,
        )

    def _networks(self, pairs) -> List[NetworkConfig]:
        """Build adapters by pairing ``-netdev`` backends with their devices."""
        backends: Dict[str, Dict[str, str]] = {}
        # `hostfwd=` may appear many times in one netdev, and a mapping keeps only the
        # last -- which silently dropped every forward but one. The raw list is kept
        # alongside for the keys that repeat (E-10).
        backend_values: Dict[str, List[str]] = {}
        for value in self._all(pairs, "-netdev"):
            options = _options(value)
            if "id" in options:
                backends[options["id"]] = options
                backend_values[options["id"]] = [
                    part[len("hostfwd=") :]
                    for part in value.split(",")
                    if part.startswith("hostfwd=")
                ]

        networks: List[NetworkConfig] = []
        for value in self._all(pairs, "-device"):
            options = _options(value)
            netdev_id = options.get("netdev")
            if not netdev_id or netdev_id not in backends:
                continue
            backend = backends[netdev_id]
            kind = backend.get("", "user")
            networks.append(
                NetworkConfig(
                    model=NIC_MODEL_FROM_QEMU.get(options.get("", ""), NicModel.E1000),
                    network_type=NETDEV_TO_NETWORK.get(kind, NetworkType.NAT),
                    adapter_name=backend.get("br"),
                    mac_address=options.get("mac"),
                    port_forwards=_hostfwd_rules(backend_values.get(netdev_id, [])),
                )
            )
        return networks


def _address(address: str):
    """Return ``(port, unit)`` from a QEMU bus address such as ``sata0.2``."""
    if not address or "." not in address:
        return (None, None)
    _, _, tail = address.partition(".")
    return (_int(tail, 0), 0)


def _int(value: Optional[str], default: int) -> int:
    """Return an integer from a command-line value, tolerating suffixes."""
    if value is None:
        return default
    digits = "".join(ch for ch in str(value) if ch.isdigit())
    return int(digits) if digits else default


def _hostfwd_rules(values: List[str]) -> List[PortForward]:
    """Return the port forwards in a netdev's ``hostfwd=`` values.

    QEMU's spelling is ``tcp:127.0.0.1:2222-10.0.2.15:22``, and either address may be
    empty: ``tcp::2222-:22`` is the common form. So the parts are found from the ends
    -- protocol first, ports last -- rather than by counting colons, which differs
    between the two forms.
    """
    rules: List[PortForward] = []
    for value in values:
        protocol, _, rest = value.partition(":")
        host, _, guest = rest.partition("-")
        host_ip, _, host_port = host.rpartition(":")
        guest_ip, _, guest_port = guest.rpartition(":")
        if not host_port.isdigit() or not guest_port.isdigit():
            continue
        rules.append(
            PortForward(
                host_port=int(host_port),
                guest_port=int(guest_port),
                protocol=protocol or "tcp",
                host_ip=host_ip,
                guest_ip=guest_ip,
            )
        )
    return rules
